// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace PolyGameplayTags
{
#pragma region InputTag
	/// RPGPOLYGON_API,允许这个标签可以被其他模块使用
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Move);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Look);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Equip);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_UnEquip);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_LightAttack);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_HeavyAttack);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Block);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_TargetLock);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_SwitchTarget_Left);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_SwitchTarget_Right);

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Click_Interact);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Click_Character);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Click_Environment);

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_InputTag_Roll);
#pragma endregion

#pragma region WeaponTag
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Weapon_KnightRuin_Staff_01);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Weapon_KnightRuin_Sword_GreatSwordRound);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Weapon_KnightRuin_Spear);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Weapon_KnightRuin_Bow);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Weapon_KnightRuin_Staff_01);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Weapon_KnightRuin_Sword_GreatSwordRound);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Weapon_KnightRuin_Spear);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Weapon_KnightRuin_Bow);

#pragma endregion


#pragma region EventTag


	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Offensive_MeleeHit);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Offensive_Spell_Projectile);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_Equip_Axe);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_UnEquip_Axe);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_HitPause);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_HitReact);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_Death);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_SuccessfulBlock);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_SwitchLockTarget_Left);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_SwitchLockTarget_Right);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_SwitchLockTarget_Right);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_Bow_Aiming);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_EventTag_Action_Bow_Release);

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_EventTag_Action_HitReact);
	/// 敌人死亡时会被授予的标签
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_EventTag_Action_Death);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_EventTag_Offensive_MeleeHit);
	/// 敌人侧走模式事件
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_EventTag_Action_Strafing);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_EventTag_Action_Bow_Aiming);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_EventTag_Action_Bow_Release);

#pragma endregion

#pragma region AbilityTag
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_SpawnWeapon_Type_Staff);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_SpawnWeapon_Type_Sword);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_SpawnWeapon_Type_Shield);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_SpawnWeapon_Type_Staff);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_SpawnWeapon_Type_Sword);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_SpawnWeapon_Type_Shield);

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_Equip_Axe);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_UnEquip_Axe);

#pragma region AbilityMainSpell
	/// Bascic Skills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_FireBolt);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Cold_FrostBolt);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_Spark);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_ArcLash);

	/// Core Skills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_Incinerate);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_Fireball);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Cold_FrozenOrb);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Cold_IceShards);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_ChainLightning);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_ChargedBolts);

	/// DefensiveSkills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_FlameShield);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_Teleport);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Defend_Spell_Cold_IceArmor);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Defend_Spell_Cold_FrostNova);

	/// Conjuration Skills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_Hydra);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Cold_IceBlades);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_LightningSpear);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_MultiElement_Familiar);

	/// Master Skills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Cold_Blizzard);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_Meteor);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_FireWall);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_BallLightning);

	/// Ultimate Skills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Cold_DeepFreeze);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Fire_Inferno);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Offensive_Spell_Lightning_UnstableCurrents);

	/// Key Passive Skills
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Physical_Enlightenment);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Physical_Combustion);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Physical_VyrsMastery);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Physical_OverflowingEnergy);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Cold_Shatter);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Cold_Avalanche);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_KeyPassive_Fire_EsusFerocity);

#pragma endregion

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Defend_Block_Shield);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_HitPause);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_HitReact);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_HitReact_Front);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_HitReact_Left);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_HitReact_Right);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_HitReact_Back);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_Death);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_Roll);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_TargetLock);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Ability_Action_ClickMove);

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Offensive_Melee);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Offensive_Ranged);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_Action_HitReact);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_Action_HitReact_Front);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_Action_HitReact_Left);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_Action_HitReact_Right);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_Action_HitReact_Back);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Ability_Action_Death);

#pragma endregion

#pragma region AbilityStatusTag

	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Status_Action_Rolling);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Status_Action_Blocking);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Status_Action_TargetLocking);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Status_Action_Move_ManualMoving);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Status_Action_Move_AutoMoving);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Player_Status_Action_Bow_Aiming);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Status_Action_UnderAttack);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Enemy_Status_Action_Bow_Aiming);

#pragma endregion

#pragma region SetByCallerTag
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Shared_SetByCaller_BaseDamage);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Shared_SetByCaller_AttackType_Light);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_Shared_SetByCaller_AttackType_Heavy);
#pragma endregion

#pragma region EuippedTag
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Current);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Right);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Left);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Back);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Head);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Bread);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Wing1);
	RPGPOLYGON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_EquippedTag_Wing2);
#pragma endregion

#pragma region MageSkillKeywords
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_AttackSpeed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Barrier);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Basic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Burn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Chain);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Channeled);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Chill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Cold);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Conjuration);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Cooldown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Core);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_CracklingEnergy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_CriticalStrikes);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_CrowdControl);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_DamageReduction);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Defensive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Dodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_EliteMonsters);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Frost);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Frozen);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Healing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Healthy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Immune);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_KeyPassive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Life);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Lightning);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_LuckyHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Mana);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Mastery);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Mobility);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Movement);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_NonPhysical);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Pyromancy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Resistance);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Shock);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Summon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Ultimate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Unstoppable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RpgPoly_SkillKeywords_Vulnerable);

#pragma endregion
}
